swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /scientificcalculator
paths:
 /src/driver/ScientificCalc/ScientificCalc/{base_val},{power_val}:
    get:
      operationId: src.driver.ScientificCalc.ScientificCalc.x_power_y
      tags:
        - x_power_y
      summary: Calculate value for x power y
      description: Calculate value for x power y
      parameters:
        - name: base_val
          in: path
          description: Provides x value
          type: integer
          required: true
        - name: power_val
          in: path
          description: Provides y value
          type: integer
          required: true
      responses:
        200:
          description: Gives value for x power y
          schema:
            properties:
              output:
                type: integer
